name: test

on: [push, pull_request]

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby-jruby
      min_version: 2.4

  test:
    needs: ruby-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - { os: windows-latest, ruby: ucrt }
          - { os: windows-latest, ruby: mingw }
          - { os: windows-latest, ruby: mswin }
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          apt-get: "haveged libyaml-dev"
          brew: libyaml
          vcpkg: libyaml
      - name: Install dependencies
        run: bundle install --jobs 1
      - name: Run test
        run: rake
      - name: Install gem
        run: rake install
